apiVersion: apps/v1
kind: Deployment
metadata:
  name: VideoProcess
  labels:
    app: VideoProcess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VideoProcess
  template:
    metadata:
      labels:
        app: VideoProcess
    spec:
      containers:
        - name: VideoProcess
          image: username/VideoProcess:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
